const $=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const links={palace:'https://www.dpm.org.cn/singles_detail/259831.html',square:'https://yuyue2026.tamgw.beijing.gov.cn/web/',lama:'https://www.yonghegong.cn/node_7175041.htm',tsinghua:'https://campusvisit.tsinghua.edu.cn/',pku:'https://visitor.pku.edu.cn/',rail:'https://www.12306.cn/',railguide:'https://jtgl.beijing.gov.cn/jgj/jgxx/94246/95332/543364982/index.html'};
const hotels=[
{id:'dongsi',name:'北京王府井绿发智选假日酒店',area:'central',district:'东四 · 礼士胡同',level:'实用舒适',address:'东城区礼士胡同18号',transport:'东四 / 朝阳门片区；先核对到地铁站的步行路线。',why:'更适合这次以老城为主的行程，雍和宫、故宫与胡同几天比较好衔接。',url:'https://www.ihg.com.cn/holidayinnexpress/hotels/cn/zh/beijing/bjsdn/hoteldetail'},
{id:'hilton',name:'北京王府井希尔顿酒店',area:'central',district:'王府井 · 金鱼胡同周边',level:'高端舒适',address:'东城区王府井东街8号',transport:'金鱼胡同 / 王府井片区，适合老城与购物行程。',why:'住在王府井商圈，首日可以轻松散步、吃饭，再慢慢适应北京。',url:'https://www.hilton.com/en/hotels/bjswfhi-hilton-beijing-wangfujing/hotel-info/'},
{id:'dongzhimen',name:'北京东直门智选假日酒店',area:'east',district:'东直门 · 春秀路',level:'实用舒适',address:'东城区春秀路1号',transport:'官网标注距东直门站约1.2公里，并非地铁口酒店。',why:'靠近东直门与三里屯方向。去老城可乘地铁，但需要预留步行或短途接驳。',url:'https://www.ihg.com/holidayinnexpress/hotels/cn/zh/beijing/pegdz/hoteldetail'},
{id:'jen',name:'JEN北京新国贸饭店',area:'east',district:'国贸 · CBD',level:'高端舒适',address:'朝阳区建国门外大街1号',transport:'国贸片区，适合第八天夜景；去海淀和长城需早出发。',why:'更偏爱城市夜景与商场的话可以选这里；多数白天的老城游览需要跨区通勤。',url:'https://www.shangri-la.com/cn/hotels/jen/beijing/centraldistrict/'},
{id:'qianmen',name:'北京前门富力智选假日酒店',area:'south',district:'南城 · 南纬路',level:'实用舒适',address:'西城区南纬路36号',transport:'南城生活区；“前门”是酒店名，不等于在前门地铁口。',why:'首日可往前门、大栅栏寻找烟火气。去海淀、奥体和清河站要多留通勤时间。',url:'https://www.ihg.com/holidayinnexpress/hotels/cn/zh/beijing/pegdr/hoteldetail'},
{id:'shangdi',name:'北京上地智选假日酒店',area:'northwest',district:'上地 · 清河站周边',level:'实用舒适',address:'海淀区上地东路33号',transport:'官网标注距清河站约499米；实际入口及步行以导航为准。',why:'园林、大学与清河出发的长城日更方便；前四天老城行程通勤会更长。',url:'https://www.ihg.com/holidayinnexpress/hotels/cn/zh/beijing/pegsd/hoteldetail'},
...window.BeijingStays.extra];
const areas={central:'东四 / 王府井',east:'东直门 / 国贸',south:'前门 / 南城',northwest:'海淀 / 上地',hutong:'什刹海 / 鼓楼',north:'奥体 / 北部'};
const defaults={hotel:null,custom:null,start:'',pace:'original',day:0,checks:{},shichahai:true,final:'both',station:'auto'};
let state={...defaults};try{const saved=JSON.parse(localStorage.getItem('beijing-notebook-v1')||'null');if(saved&&typeof saved==='object')state={...defaults,...saved,checks:saved.checks||{}}}catch{}
if(!Number.isInteger(state.day)||state.day<0||state.day>8)state.day=0;
if(!['original','balanced','relaxed'].includes(state.pace))state.pace='original';
if(!['both','bird','bridge'].includes(state.final))state.final='both';
if(!['auto','qinghe','beijingbei'].includes(state.station))state.station='auto';
if(!/^\d{4}-\d{2}-\d{2}$/.test(state.start)||!Number.isFinite(new Date(state.start+'T12:00:00').getTime()))state.start='';
function save(){try{localStorage.setItem('beijing-notebook-v1',JSON.stringify(state))}catch{toast('当前浏览器无法保存；本次仍可正常规划。')}}
function hotel(){return state.hotel==='custom'&&state.custom&&areas[state.custom.area]?state.custom:hotels.find(h=>h.id===state.hotel)}
function toast(t){$('#toast').textContent=t;$('#toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').hidden=true,3500)}
function dayDate(i){if(!state.start)return null;let d=new Date(state.start+'T12:00:00');d.setDate(d.getDate()+i);return d}
function dateLabel(i){let d=dayDate(i);return d?`${d.getMonth()+1}.${String(d.getDate()).padStart(2,'0')} 周${'日一二三四五六'[d.getDay()]}`:''}
function swapPalace(){return dayDate(2)?.getDay()===1}
function dayType(i){return swapPalace()?(i===2?3:i===3?2:i):i}
const S=(time,title,description,destination)=>({time,title,description,destination});
const routeData=[
{label:'初见北京',title:'先安顿，再逛逛',effort:'轻松 · 约 3–5 km',caption:'把第一天，留给北京的烟火气。',start:15*60,target:'什刹海',summary:'抵达日 · 不赶早',note:'抵达较晚就只在酒店附近吃饭。烤鸭、炸酱面、铜锅涮肉任选一种，别把第一餐变成打卡任务。'},
{label:'古都文脉',title:'在古树与胡同间走走',effort:'适中 · 约 5–7 km',caption:'循着胡同，走进老北京。',start:9*60,target:'地坛公园',summary:'地坛 → 雍和宫 → 国子监',stops:[S('09:00 · 1.5小时','地坛公园','先在古树下散步，保留体力。公园具体入园时间与活动安排以当天公告为准。','地坛公园'),S('11:00 · 约2小时','雍和宫','按预约时段入内。地坛到雍和宫可步行衔接，适当留出安检排队时间。','雍和宫'),S('14:00 · 2小时','国子监街与五道营胡同','午饭后逛国子监街，想坐下就找间小店。若进孔庙和国子监博物馆，另查门票及开放日；街区散步不等同于入馆。','国子监街')],note:'午饭可以选炸酱面、门钉肉饼；下午来一份豌豆黄或驴打滚。具体餐厅到附近后按营业情况选择。'},
{label:'紫禁城里',title:'沿着中轴，走进紫禁城',effort:'较累 · 约 7–10 km',caption:'红墙金瓦，是这座城的时间。',start:8*60+30,target:'天安门广场',summary:'天安门广场 → 午门 → 故宫',stops:[S('08:30 · 约1.5小时','天安门广场','按已预约时段参观，预留安检缓冲。这条路线不包含登天安门城楼；登楼需另查开放和预约。','天安门广场'),S('10:30 · 4–5小时','故宫博物院','从午门入院，沿太和殿、乾清宫、御花园方向游览。以实际购票时段为准，带水和轻便食物，中途坐下休息。','故宫博物院午门'),S('16:00 左右','神武门出院，早点回去','从神武门或东华门离开。今天不再增加登山，景山登顶留到另一日。','故宫博物院神武门')],note:'故宫一般周一闭馆（法定节假日除外），提前7日20:00放票，不售当日票。广场、故宫和城楼的预约范围不同，请分别确认。'},
{label:'登高入巷',title:'登上景山，把北京看一遍',effort:'适中 · 约 5–7 km',caption:'从万春亭，看见整座紫禁城。',start:9*60,target:'景山公园南门',summary:'景山登顶 → 南锣鼓巷',stops:[S('09:00 · 1.5–2小时','景山公园 · 登顶万春亭','这一天的必做项。慢慢走台阶，登顶俯瞰故宫；遇雨雪湿滑时以安全和现场管理为先。','景山公园南门'),S('12:00 · 午饭与休息','午间找个地方坐坐','登顶后给双腿放个假。午饭后再去南锣，不必把沿途每条胡同都走完。','南锣鼓巷'),S('14:00 · 2–3小时','南锣鼓巷与周边胡同','主街热闹，侧巷更安静。尊重居民生活，不进入私人院落。体力好再去鼓楼方向看看。','南锣鼓巷')],note:'若故宫原定日遇周一，网页会把这天与故宫日对调；法定节假日特殊开放仍需自行核对。'},
{label:'皇家园林',title:'把一天，交给湖光山色',effort:'很累 · 约 10–15 km',caption:'园林很大，不必一天走完。',start:8*60+30,target:'颐和园东宫门',summary:'颐和园 → 圆明园',stops:[S('08:30 · 4小时','颐和园','从东宫门方向入园，选长廊与昆明湖一段慢走。避免为了“走全”绕湖一大圈；码头和游船受季节天气影响。','颐和园东宫门'),S('12:30 · 1小时','午饭、休息、转场','先坐下来吃饭，再前往圆明园。转场用地图确认当前路线。','圆明园南门'),S('14:00 · 2–3小时','圆明园','只选一条重点路线；想看西洋楼遗址需核对相应票种。走不动就切到“轻松一点”，移到明天。','圆明园南门')],note:'同一天两座大园很费腿。轻松模式会把圆明园移到第六天，校园参观改为可选；九天总长度不变。'},
{label:'漫步学府',title:'去看看，理想里的校园',effort:'适中 · 约 4–7 km',caption:'今天的路，慢一点也很好。',start:9*60,target:'北京大学东侧门',summary:'北大 / 清华 · 以预约为先',stops:[S('按预约时段 · 上午','北京大学','只有预约成功后才安排入校。按官方指定入口核验；常规开放多在双休日、法定节假日与寒暑假。','北京大学东侧门'),S('中午 · 至少1小时','五道口或中关村用餐','两所学校之间预留交通和午餐时间。校园很大，不要把两场入校预约排得太紧。','五道口'),S('按预约时段 · 下午','清华大学','按“参观清华”的有效预约入校，路线以指定校门为准。若两校只约到一所，就把时间留给那一所。','清华大学')],note:'没有预约：改为校外街区散步、五道口吃饭或回酒店休息，不能保证现场入校。校园参观免费，勿购买所谓“包入校”。'},
{label:'长城一日',title:'今天，做一回好汉',effort:'较累 · 约 5–9 km',caption:'去长城，把目光放远一点。',start:7*60+30,target:'清河站',summary:'高铁往返 · 八达岭长城',note:'高铁目的地请选“八达岭长城”，与S2线的“八达岭”站不同。车次、票价和返程终到站以12306为准；清河出发并不保证始终最便宜。'},
{label:'城市夜色',title:'睡个懒觉，等城市亮灯',effort:'轻松 · 约 2–4 km',caption:'白天留白，夜晚留给城市。',start:18*60,target:'国贸商城',summary:'白天休息 → 国贸夜景',stops:[S('白天 · 自由安排','休息，也是一种旅行','睡到自然醒，洗衣、整理照片，或在酒店周围吃点东西。今天不安排需要赶时间的景点。'),S('18:00 · 2–3小时','国贸商圈与CBD夜景','在国贸商城吃晚饭，去公共可达区域看看高楼与夜景。露台是否开放、是否消费入场，以商场当日规则为准。','国贸商城'),S('20:30 左右','早点回酒店','第二天还有行程，给返程或继续游览留一些体力。')],note:'不保证灯光秀、露台或高层观景点开放。下雨时直接在商场吃饭逛逛，也很好。'},
{label:'告别北京',title:'给北京，留一个回望',effort:'较累 · 跨城转场',caption:'想看的风景，可以留一点给下次。',start:9*60,target:'卢沟桥',summary:'卢沟桥 → 鸟巢外观',note:'卢沟桥在西南，鸟巢在北部，并不顺路。两处都去，跨城公共交通建议预留约90–120分钟（规划估算）；若当天返程，优先只选一处。'}];
const routeProfiles={
original:{name:'全景紧凑',tag:'体力好',summary:'第五天颐和园＋圆明园，第六天北大＋清华。两天都很满，预约需配合。',days:'D5 两园同日 · D6 两校同日'},
balanced:{name:'均衡分区',tag:'推荐',summary:'第五天颐和园＋北大，第六天圆明园＋清华；每天一园一校，转场更短。',days:'D5 颐和园＋北大 · D6 圆明园＋清华'},
relaxed:{name:'省腿慢游',tag:'更轻松',summary:'第五天只去颐和园，第六天圆明园后按预约选一所校园，不强行走完。',days:'D5 颐和园 · D6 圆明园＋一所校园'}
};
$('.controls').insertAdjacentHTML('afterend',`<section class="route-profiles" id="route-profiles" aria-labelledby="route-profiles-title"><div class="route-profiles-head"><div><div class="eyebrow">THREE WAYS TO TRAVEL</div><h2 id="route-profiles-title">选一条适合体力和预约的路线。</h2></div><p>录入预约后，自动排程会固定入场时间；尚未约到的校园先列为备选。</p></div><div class="route-profile-grid" id="route-profile-grid" role="radiogroup" aria-label="九日路线方案"></div></section>`);
function updateRouteProfileSelection(){$('#route-profile-grid').innerHTML=Object.entries(routeProfiles).map(([id,p])=>`<button class="route-profile ${state.pace===id?'selected':''}" data-route-profile="${id}" role="radio" aria-checked="${state.pace===id}"><span class="route-profile-top"><strong>${p.name}</strong><b>${p.tag}</b></span><span>${p.summary}</span><small>${p.days}</small></button>`).join('');}
updateRouteProfileSelection();
function getDay(index){return window.BeijingFeatures?.day(index)||getOriginalDay(index)}
function getOriginalDay(index){const type=dayType(index),r=structuredClone(routeData[type]),h=hotel(),area=h?.area||'central';r.type=type;r.index=index;
if(type===0){const places={central:['王府井 / 东四','王府井'],east:state.hotel==='jen'?['国贸周边','国贸商城']:['东直门 / 簋街','簋街'],south:['前门与大栅栏','前门大街'],northwest:['上地或五道口','五道口'],hutong:['鼓楼与什刹海','鼓楼'],north:['奥体周边','奥林匹克公园']};const p=places[area];r.target=p[1];r.summary=`酒店 → ${p[0]}${state.shichahai?' → 什刹海（可选）':''}`;r.stops=[S('抵达后 · 先安顿',h?h.name:'到酒店放下行李','办理入住，休息一下。当天活动以实际到达时间为准。'),S('下午 / 晚饭','从'+p[0]+'开始','先在住处所在片区散步，尝尝炸酱面、烤鸭或铜锅涮肉。餐厅和价格在到店前确认。',p[1])];if(state.shichahai)r.stops.push(S('傍晚 · 可选1–2小时','什刹海，沿湖慢慢走',area==='northwest'||area==='south'?'今天从住处去什刹海需要跨区，抵达晚就取消，留到景山或胡同那天再决定。':'走一小段前海与银锭桥周边，坐下来吹吹风。累了就提前结束。','什刹海'));}
if(type===4&&state.pace==='balanced'){r.title='颐和园与北大，湖光接着书卷';r.target='颐和园东宫门';r.effort='较累 · 约 8–11 km';r.summary='颐和园 → 午饭 → 北京大学';r.stops=[S('08:30 · 约4小时','颐和园','从东宫门方向入园，走长廊与昆明湖的一段；不绕湖一整圈，给下午校园预约留体力。','颐和园东宫门'),S('12:30 · 约1小时','午饭与短途转场','先坐下吃饭，再前往北大预约指定入口。不要把两段之间排得过紧。','北京大学东侧门'),S('下午 · 预约成功才入校','北京大学','按预约时段和指定校门核验。若只约到上午，实际行程以预约为准，网页预约排程会自动换序。','北京大学东侧门')];r.note='均衡分区方案把两座园林和两所校园拆成两个海淀日。校园没有有效预约就改为校外散步，不购买所谓“包入校”。';}
if(type===5&&state.pace==='balanced'){r.label='园林与学府';r.title='圆明园与清华，留足预约弹性';r.target='圆明园南门';r.effort='适中偏累 · 约 7–10 km';r.summary='圆明园 → 午饭 → 清华大学';r.stops=[S('09:00 · 约3小时','圆明园','从南门方向入园，只选一条重点路线；西洋楼遗址区域的票种与开放以当天为准。','圆明园南门'),S('12:15 · 约1小时','午饭与休息','圆明园与清华相邻，但校园入口受预约管理，按指定校门安排转场。','清华大学'),S('下午 · 预约成功才入校','清华大学','按“参观清华”预约时段入校。若预约在上午，先去清华，再把圆明园放到下午并缩短园内路线。','清华大学')];r.note='清华个人参观按开放日和预约时段执行，周一通常为校园休整日；遇校内活动或极端天气可能暂停。已填预约后，预约排程会固定入场时间。';}
if(type===4&&state.pace==='relaxed'){r.title='今天，只逛颐和园';r.effort='适中 · 约 5–8 km';r.summary='颐和园一日 · 圆明园留到明天';r.stops=r.stops.slice(0,1).concat([S('13:00 · 午饭后','昆明湖边慢慢走','选一段喜欢的湖岸或在长廊休息。下午随体力结束，不再转场圆明园。','颐和园')]);}
if(type===5&&state.pace==='relaxed'){r.label='园林续篇';r.title='圆明园，再留一点校园时光';r.target='圆明园南门';r.effort='适中 · 约 5–8 km';r.summary='圆明园 → 一所校园（可选）';r.stops=[S('09:00 · 3–4小时','圆明园','把昨天没走的园林留到今天。西洋楼遗址区域是否包含在票内，请在购票时核对。','圆明园南门'),S('13:00 · 午饭与休息','给下午留一点弹性','午饭后按体力和已预约时段决定是否进校园；不强求清华、北大都去。','五道口'),S('下午 · 预约成功才去','清华 / 北大，选择一所','若没有预约或已经疲惫，就在校外街区散步或回酒店。两校都入内与园林拆两天不能同时轻松完成。','北京大学东侧门')];}
if(type===6){const station=state.station==='qinghe'?'清河站':state.station==='beijingbei'?'北京北站':['northwest','north'].includes(area)?'清河站':'北京北站';r.target=station;r.summary=`${station} → 八达岭长城 → 返程`;r.stops=[S('早晨 · 按车次提前到站',station+'出发','提前买好往返车票。建议至少预留45分钟到站缓冲，再叠加酒店到车站的交通；以铁路实际检票要求为准。',station),S('上午至下午 · 3–4小时','八达岭长城','按体力选北线或南线，不追求全走完。可以另购缆车等项目，运营受天气影响；缆车也不能免去所有台阶。','八达岭长城'),S('返程 · 预留足够进站时间','返回'+(area==='northwest'?'清河站':'北京北站或清河站'),'优先选有合适车次、到酒店方便的终点。北京北靠近西直门；回程能否直达以车票为准。八达岭长城站进站通道较深，不要踩点。',area==='northwest'?'清河站':'北京北站')];}
if(type===8){const bridge=S('上午 · 约2小时','卢沟桥','看桥上的石狮与永定河风景。桥面参观、周边场馆与开放时段分别核对。','卢沟桥'),bird=S('下午 / 傍晚 · 1–2小时','鸟巢外观与奥林匹克公园','以建筑外观和周边散步为主，不包含场馆内部参观；演出或赛事可能影响通行。','国家体育场鸟巢');r.stops=state.final==='bird'?[{...bird,time:'下午 · 1–2小时'}]:state.final==='bridge'?[bridge]:[bridge,S('中午 · 约90–120分钟转场','午餐后，跨城去奥体','公共交通耗时为规划估算，不含突发延误；出发时请查实时导航。','国家体育场鸟巢'),bird];if(state.final==='both'&&area==='south'){r.stops=[{...bird,time:'上午 · 1–2小时'},S('中午 · 约90–120分钟转场','从北部前往西南','先去较远的鸟巢，再往卢沟桥方向。若要返程，以实际车站或机场安排优先。','卢沟桥'),{...bridge,time:'下午 · 约2小时'}];}r.target=r.stops[0].destination;r.summary=r.stops.filter(x=>!x.title.includes('转场')&&!x.title.includes('前往')&&!x.title.includes('跨城')).map(x=>x.title).join(' → ');if(state.final!=='both'){r.effort='轻松 · 约 3–5 km';r.start=state.final==='bird'?14*60:9*60;}}
return r;}
function commute(r){const area=hotel()?.area||'central',city={central:35,east:50,south:55,northwest:80,hutong:35,north:65},nw={central:80,east:95,south:100,northwest:35,hutong:75,north:60};let n=[4,5].includes(r.type)?nw[area]:city[area];if(r.type===6)n=r.target==='清河站'?{central:75,east:85,south:90,northwest:20,hutong:65,north:50}[area]:{central:40,east:60,south:55,northwest:55,hutong:30,north:60}[area];if(r.type===7)n=state.hotel==='jen'?15:{central:40,east:35,south:60,northwest:95,hutong:55,north:70}[area];if(r.type===8)n=r.target==='卢沟桥'?{central:85,east:105,south:65,northwest:100,hutong:95,north:110}[area]:{central:60,east:65,south:80,northwest:60,hutong:45,north:25}[area];return n;}
function departure(r){const min=r.start-commute(r)-(r.type===6?45:0);return `${String(Math.floor(min/60)).padStart(2,'0')}:${String(min%60).padStart(2,'0')}`}
function mapUrl(from,to){const place=n=>n.startsWith('北京')?n:'北京'+n;return 'https://api.map.baidu.com/direction?'+new URLSearchParams({origin:place(from),destination:place(to),mode:'transit',region:'北京',output:'html',src:'beijing-notebook'}).toString();}
function routeAdvice(r){if(r.generated)return r.departureText;let a=hotel()?`从${hotel().name}出发。`:'暂按东四 / 王府井片区规划；选酒店后会更新。';if(r.type!==0)a+=`建议 ${departure(r)} 左右出门，首段交通预留约 ${commute(r)}–${commute(r)+20} 分钟（规划估算）。`;else a+='抵达日优先逛住处附近，再决定是否去什刹海。';if(r.type===5)a+=' 校园以已约到的时段为准，出门时间仅作参考。';if(r.type===6)a+=' 出门时间按07:30车次示例，请随实际车票调整。';if(swapPalace())a+=' 原定故宫日遇周一，已与景山日对调；节假日特殊开放需核对。';return a;}
function render(){const r=getDay(state.day),h=hotel();$('#start-date').value=state.start;$('#pace').value=state.pace;$('#hotel-label').textContent=h?h.name:'还没订酒店 · 先选个住处';$('#day-nav').innerHTML=routeData.map((_,i)=>{const d=getDay(i);return `<button class="day-tab ${i===state.day?'active':''}" data-day="${i}" aria-current="${i===state.day?'step':'false'}"><small>DAY</small><b>${String(i+1).padStart(2,'0')}</b><span>${d.label}</span>${state.start?`<span class="tab-date">${dateLabel(i)}</span>`:''}</button>`}).join('');$('#day-kicker').textContent=`DAY ${String(state.day+1).padStart(2,'0')} · ${r.label}${state.start?' / '+dateLabel(state.day):''}`;$('#day-title').textContent=r.title;$('#effort').textContent=r.effort;$('#banner-caption').textContent=r.caption;$('#adjustment').textContent=routeAdvice(r);$('#route-summary').textContent=r.summary;$('#day-count').textContent=`${String(state.day+1).padStart(2,'0')} / 09`;$('#previous').disabled=state.day===0;$('#next').disabled=state.day===8;let prev=h?.name||'东四地铁站';$('#timeline').innerHTML=r.stops.map((s,i)=>{const url=s.destination&&s.destination!==prev?mapUrl(prev,s.destination):'';if(s.destination)prev=s.destination;return `<article class="stop"><span class="stop-number">${String(i+1).padStart(2,'0')}</span><div><small>${esc(s.time)}</small><h3>${esc(s.title)}</h3><p>${esc(s.description)}</p>${url?`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">查看这一段交通 ↗</a>`:''}</div></article>`}).join('');$('#day-note').innerHTML=`<strong>留意这件事</strong><br>${esc(r.note)}${r.type===0?`<label class="inline-choice"><input type="checkbox" id="shichahai" ${state.shichahai?'checked':''}>把什刹海作为今晚的可选项</label>`:''}${r.type===6||r.hasWall?`<label class="inline-choice">出发车站 <select id="station"><option value="auto">按住处推荐</option><option value="qinghe">清河站</option><option value="beijingbei">北京北站</option></select></label><a href="${links.rail}" target="_blank" rel="noopener noreferrer">12306 查车次与票价 ↗</a>`:''}${r.type===8||(r.generated&&state.day===8)?`<label class="inline-choice">最后一天 <select id="final-choice"><option value="both">两处都去（跨城）</option><option value="bird">轻松一点 · 只看鸟巢</option><option value="bridge">只去卢沟桥</option></select></label>`:''}`;if($('#station'))$('#station').value=state.station;if($('#final-choice'))$('#final-choice').value=state.final;
$('#stay-description').textContent=h?h.why:'第一次来，可以先看看东四、王府井一带。市区几天的行程比较好衔接。';$('#stay-details').innerHTML=h?`${esc(h.address||areas[h.area])}<br>${esc(h.transport||'自填住处按片区粗略规划，具体通勤请点交通链接核实。')}`:'';$('#change-hotel').textContent=h?'换个住处，重新规划 ↗':'挑选我的酒店 ↗';renderChecklist();window.BeijingFeatures?.refresh();}
function renderChecklist(){let palaceIndex=swapPalace()?3:2;let d=dayDate(palaceIndex),release='提前7日 20:00';if(d){d.setDate(d.getDate()-7);release=`${d.getMonth()+1}月${d.getDate()}日 20:00 放票`;}const items=[['palace','故宫预约 · '+release,links.palace],['square','确认天安门广场预约',links.square],['lama','雍和宫预约与开放安排',links.lama],['school','确认清华 / 北大开放日',links.tsinghua],['rail','买好长城往返车票',links.rail],['id','有效证件、舒适的鞋和水','']];$('#checklist').innerHTML=items.map(([id,title,url])=>`<div class="check ${state.checks[id]?'done':''}"><input type="checkbox" id="check-${id}" data-check="${id}" ${state.checks[id]?'checked':''}><span><label for="check-${id}">${esc(title)}</label>${url?`<a target="_blank" rel="noopener noreferrer" href="${url}">官方入口 ↗</a>`:''}</span></div>`).join('');}
function renderHotels(){const filter=$('#area-filter').value;$('#hotel-list').innerHTML=hotels.filter(h=>filter==='all'||h.area===filter).map(h=>`<article class="hotel-card ${state.hotel===h.id?'selected':''}"><span class="area-tag">${h.district} · ${h.level}</span><h3>${h.name}</h3><p>${h.address}</p><p>${h.transport}</p><p>${h.why}</p><div class="hotel-actions"><a href="${h.url}" target="_blank" rel="noopener noreferrer">查看房源 / 实时价 ↗</a><button data-hotel="${h.id}">${state.hotel===h.id?'已选择':'以这里为起点'}</button></div></article>`).join('');}
function selectHotel(id){if(!hotels.some(h=>h.id===id))throw new Error('请选择列表中的有效酒店');state.hotel=id;save();render();renderHotels();if($('#hotel-dialog').open)$('#hotel-dialog').close();toast('已按住处更新九日行程');}
function setDay(i){state.day=i;save();render();}
function selectRouteProfile(value){if(!routeProfiles[value])return;state.pace=value;save();render();updateRouteProfileSelection();toast(state.plannerEnabled?'已按新路线重排；预约时段仍保持不变':value==='balanced'?'已切换为均衡分区：每天一园一校':value==='relaxed'?'已切换为省腿慢游：一天一园，校园择一':'已切换为全景紧凑路线');}
$('#day-nav').onclick=e=>{const b=e.target.closest('[data-day]');if(b)setDay(Number(b.dataset.day));};$('#previous').onclick=()=>setDay(Math.max(0,state.day-1));$('#next').onclick=()=>setDay(Math.min(8,state.day+1));$('#start-date').onchange=e=>{state.start=e.target.value;save();render();if(!state.plannerEnabled&&swapPalace())toast('已避开周一：故宫与景山日对调');};$('#pace').onchange=e=>selectRouteProfile(e.target.value);$('#route-profile-grid').onclick=e=>{const b=e.target.closest('[data-route-profile]');if(b)selectRouteProfile(b.dataset.routeProfile);};
$('#choose-hotel').onclick=$('#change-hotel').onclick=()=>{renderHotels();$('#hotel-dialog').showModal()};$('#close-dialog').onclick=()=>$('#hotel-dialog').close();$('#area-filter').onchange=renderHotels;$('#hotel-list').onclick=e=>{const b=e.target.closest('[data-hotel]');if(b)selectHotel(b.dataset.hotel);};
$('#custom-form').onsubmit=e=>{e.preventDefault();let name=$('#custom-name').value.trim();if(!name){$('#custom-name').setCustomValidity('请输入酒店名称');$('#custom-name').reportValidity();return;}$('#custom-name').setCustomValidity('');const area=$('#custom-area').value;state.custom={id:'custom',name,area,why:`按${areas[area]}片区安排出发。自填住处未进行地址核验，请在导航中确认位置后出发。`};state.hotel='custom';save();render();$('#hotel-dialog').close();toast('已按自填酒店的片区更新行程');};$('#custom-name').oninput=e=>e.target.setCustomValidity('');
$('#day-note').onchange=e=>{if(e.target.id==='shichahai')state.shichahai=e.target.checked;if(e.target.id==='station')state.station=e.target.value;if(e.target.id==='final-choice')state.final=e.target.value;save();render();};$('#checklist').onchange=e=>{if(e.target.dataset.check){state.checks[e.target.dataset.check]=e.target.checked;save();renderChecklist();window.BeijingFeatures?.refresh();}};
function itineraryText(){return `京日慢游 · 北京九日旅行手册\n住处：${hotel()?.name||'暂按东四 / 王府井规划'}\n路线：${routeProfiles[state.pace].name} · ${routeProfiles[state.pace].days}\n${state.start?'出发：'+state.start:'日期待定'}\n\n`+routeData.map((_,i)=>{const r=getDay(i);return `第${i+1}天 ${dateLabel(i)}｜${r.title}\n${routeAdvice(r)}\n${r.stops.map(s=>s.time+' '+s.title+'\n'+s.description).join('\n')}\n提醒：${r.note}`}).join('\n\n')+'\n\n交通时间、步行距离为规划估算，不是实时导航。住宿价格、票务及校园开放以出行当天信息为准。\n官方入口：\n'+Object.entries(links).map(([k,v])=>k+': '+v).join('\n');}
$('#export').onclick=()=>{const blob=new Blob(['\ufeff'+itineraryText()],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='北京九日旅行手册.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);toast('已导出当前酒店与节奏下的九日行程');};
$('#banner').style.backgroundImage='url("beijing.jpg")';$('#banner').setAttribute('role','img');$('#banner').setAttribute('aria-label','从景山俯瞰故宫的真实全景照片');
$('#sources-content').innerHTML=`<div class="source-grid">${[['故宫 · 购票与周一闭馆说明',links.palace],['天安门广场 · 官方预约',links.square],['雍和宫 · 官方开放与购票',links.lama],['清华 · 校园参观',links.tsinghua],['北大 · 校园参观',links.pku],['铁路12306 · 实时车次票价',links.rail],['北京交管 · 八达岭铁路出行说明',links.railguide]].map(([n,u])=>`<a href="${u}" target="_blank" rel="noopener noreferrer">${n} ↗</a>`).join('')}</div><p>住宿名称、地址与参考价来自各品牌官网及房源平台页面，资料更新至2026年9月23日；部分参考价是更早日期的页面快照。订房时请核对地址、房型和营业状态。住宿片区按床位和房间分别显示收录样本的高低价，不代表实时库存。</p><p>路线按住处片区做规则调整：首日选择附近活动、每日首段通勤与出门时间、长城出发站、第九天的顺序；不是实时地图最优路径计算。公交时间与步行距离均为宽范围规划估算，节假日和高峰期应额外留时。校园按实际预约时段执行；各景点开放、票种与预约规则以出行当天官方信息为准。</p><p>三条路线都保留长城日、第八天白天休息和故宫周一回避。全景紧凑把两园、两校分别压在一天；均衡分区把颐和园与北大、圆明园与清华分为两天；省腿慢游一天一园并把校园改为择一。任何校园都须预约成功才入校，日期变化不会替你更改门票或车票。</p><p>照片：<a target="_blank" rel="noopener noreferrer" href="https://commons.wikimedia.org/wiki/File:%E6%99%AF%E5%B1%B1%E5%85%AC%E5%9B%AD_(19687188164)_-_panorama.jpg">故宫全景，Han Zheng / Wikimedia Commons</a>，<a target="_blank" rel="noopener noreferrer" href="https://creativecommons.org/licenses/by-sa/2.0/">CC BY-SA 2.0</a>。网页展示时裁切并叠加渐变，图片及其改编沿用该许可。</p>`;
render();
if(document.modelContext?.registerTool){const life=new AbortController();const register=t=>{try{Promise.resolve(document.modelContext.registerTool(t,{signal:life.signal})).catch(()=>{})}catch{}};register({name:'read_beijing_itinerary',description:'Read the selected hotel, route profile and full nine-day Beijing itinerary.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>({hotel:hotel()?.name||null,routeProfile:routeProfiles[state.pace].name,days:routeData.map((_,i)=>{let d=getDay(i);return {day:i+1,title:d.title,route:d.summary,advice:routeAdvice(d)}})})});register({name:'configure_beijing_trip',description:'Choose one of the listed hotel IDs, route profiles or displayed day. Updates the visible plan and this browser’s saved preferences; does not book travel.',inputSchema:{type:'object',properties:{hotelId:{type:'string',enum:hotels.map(h=>h.id)},pace:{type:'string',enum:['original','balanced','relaxed']},day:{type:'integer',minimum:1,maximum:9}},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:input=>{if(!input||typeof input!=='object'||Array.isArray(input))throw new Error('Expected an object');if(Object.keys(input).some(k=>!['hotelId','pace','day'].includes(k)))throw new Error('Unknown field');if(input.hotelId!==undefined&&!hotels.some(h=>h.id===input.hotelId))throw new Error('Unknown hotel');if(input.pace!==undefined&&!['original','balanced','relaxed'].includes(input.pace))throw new Error('Invalid route profile');if(input.day!==undefined&&(!Number.isInteger(input.day)||input.day<1||input.day>9))throw new Error('Day must be 1–9');if(input.hotelId!==undefined)state.hotel=input.hotelId;if(input.pace!==undefined)state.pace=input.pace;if(input.day!==undefined)state.day=input.day-1;save();render();updateRouteProfileSelection();return {hotel:hotel()?.name||null,routeProfile:routeProfiles[state.pace].name,pace:state.pace,day:state.day+1,title:getDay(state.day).title};}});window.addEventListener('pagehide',()=>life.abort(),{once:true});}
