/* Reservations and hotel-price map share the notebook's state and renderer. */
(()=>{
'use strict';
const P=window.TripPlanner;
if(!P)return;
state.reservations=Array.isArray(state.reservations)?state.reservations.filter(b=>b&&typeof b==='object'):[];
state.quotes=state.quotes&&typeof state.quotes==='object'?state.quotes:{};
state.stayDates=state.stayDates&&typeof state.stayDates==='object'?state.stayDates:{in:'',out:''};
state.plannerEnabled=!!state.plannerEnabled;
const hotelData={
dongsi:{lat:39.921711,lon:116.424388,price:902.48,source:'Booking.com 页面参考',context:'页面所示起价；未指定入住日期，房型及税费口径需另查。',url:'https://www.booking.com/district/cn/beijing/wangfujingshoppingarea.zh-tw.html',locationSource:'https://www.travelmyth.co.uk/Beijing/Hotels/Holiday-Inn-Express-Beijing-Downtown-by-IHG_tmid6531157',locationNote:'第三方地图参考点，坐标可能偏移，请以酒店地址导航。'},
hilton:{lat:39.9133817,lon:116.4070196,price:975,source:'希尔顿官网列表',context:'官网所示会员起价，页面标注含费用；适用日期及会员条件以官网为准。',url:'https://www.hilton.com/zh-hans/locations/china/beijing/hilton-hotels/?sortBy=BRAND',locationSource:'https://www.openstreetmap.org/way/368736558'},
dongzhimen:{lat:39.9353898,lon:116.4372379,price:743.91,source:'Booking.com 页面参考',context:'页面曾展示的每晚平均价；日期、房型与税费未核定。',url:'https://www.booking.com/holidayinn/city/cn/beijing.zh-tw.html',locationSource:'https://www.openstreetmap.org/way/350503513'},
jen:{lat:39.9116585,lon:116.4547004,price:1053,source:'Klook 客路页面',context:'页面标注近30天低价，参考9月27日；不是当前所选日期的报价，税费请另核实。',url:'https://www.klook.cn/zh-CN/hotels/detail/619628-jen-beijing-by-shangrila/',locationSource:'https://www.openstreetmap.org/node/7530416949'},
qianmen:{lat:39.8789694,lon:116.3847307,price:534.6,source:'Klook 客路页面',context:'页面标注近30天低价，参考8月28日；不是当前所选日期的报价，税费请另核实。',url:'https://www.klook.cn/zh-CN/hotels/detail/396582-holiday-inn-express-beijing-temple-of-heaven-by-ihg/',locationSource:'https://www.openstreetmap.org/node/4396996089'},
shangdi:{lat:40.0353871,lon:116.3083873,price:753,source:'中国假日旅游网页面',context:'页面所示起价；未指定入住日期，房型及税费口径需另查。',url:'https://www.chinaholiday.com/big5/city_104/21700.html',locationSource:'https://www.openstreetmap.org/way/659220912'}
};
const descriptions={ditan:'在古树下散步，保留体力。',lama:'按有效票面时段入内，预留安检排队时间。',guozijian:'街区慢走，想入孔庙和国子监博物馆需另核对开放日及门票。',square:'确认广场预约与安检入口；这里不含天安门城楼登楼。',palace:'午门入院，神武门或东华门出院。长时间游览内安排午餐和坐下休息。',jingshan:'一定慢慢登上万春亭，看故宫全景；遇雨雪湿滑以现场管理为准。',nanluo:'主街与侧巷按体力选择，不进入私人院落。',summer:'选长廊与昆明湖重点一段，不强求绕湖一周；游览内安排午餐。',yuanming:'选重点路线，西洋楼遗址区域须核对对应票种。',pku:'仅在预约成功且当天开放时入校；未约到可在校外街区散步或休息。',tsinghua:'仅在预约成功且当天开放时入校，入口以票面为准。',wall:'往返车票另购，目的地为“八达岭长城站”。跨区交通预留只是估算，须按实际车次倒推；途中安排午餐。',guomao:'公共可达区域赏夜景，露台开放及消费规定以商场当日规则为准。',bird:'以场馆外观和公共区域散步为主，赛事可能影响通行。',bridge:'桥面与周边场馆分别核对开放时段。'};
let view='route',map=null,markers=[],mapWaiting=false,editing=null,cacheKey='',cachePlan=null,refreshing=false;
function plan(){if(!state.plannerEnabled)return null;const h=hotel(),home=hotelData[h?.id]||P.AREA_HOME[h?.area]||P.AREA_HOME.central;const key=JSON.stringify([state.start,state.reservations,state.pace,state.final,home]);if(key!==cacheKey){cachePlan=P.build({start:state.start,reservations:state.reservations,pace:state.pace,final:state.final,home});cacheKey=key;}return cachePlan;}
function plannedDay(i){const result=plan();if(!result||!Number.isFinite(P.dateNumber(state.start)))return null;const items=result.days[i],base=getOriginalDay(i);if(i===0&&!items.length){base.note+=' 已预约景点按你填写的时间优先安排。';return base;}const booked=items.filter(x=>x.locked),first=items[0];let note='按输入的预约时间生成；其余游览时段为保守建议，并非官方开放时间。长时游览中自行安排餐饮休息。';if(result.issues.length)note+=' 尚有预约冲突：'+result.issues.join(' ');if(!first)return {...base,type:-1,label:'留白休息',title:'今天留一点自由时间',summary:'休息 / 自由安排',effort:'轻松 · 自由安排',start:600,generated:true,departureText:'今天没有排入固定景点，可以休息或从待安排清单挑选。',stops:[S('自由安排','休息或补充未排入的景点','在“我的预约”查看待安排清单，不要在已预约的日子临时加塞。')],note};
const stops=items.map(x=>S(`${P.clock(x.start)}–${P.clock(x.end)} · ${x.locked?'已预约':'建议'}${x.travelBefore?' / 前段约'+x.travelBefore+'分钟':''}`,x.name,descriptions[x.id]+(x.locked?' 入场时间已锁定，网页不会更改实际预约。':''),x.id==='palace'?'故宫博物院午门':x.id==='pku'?'北京大学东侧门':x.id==='wall'?'八达岭长城站':x.name.replace('（须预约成功）','')));
const departureTime=P.clock(Math.max(0,first.start-first.travelBefore-15));
return {...base,type:-1,label:booked.length?'有预约':'已重排',title:items.length===1?first.name.replace('（须预约成功）',''):first.name.replace('（须预约成功）','')+'，再慢慢走',summary:items.map(x=>x.name.replace('（须预约成功）','')).join(' → '),effort:items.some(x=>x.id==='wall')?'较累 · 长城日':items.reduce((n,x)=>n+x.duration,0)>420?'较累 · 安排较满':'按预约 · 留有转场',stops,note:note+(items.some(x=>x.id==='wall')?' 长城交通：'+getOriginalDay(6).stops.filter(x=>x.title.includes('站')||x.title.includes('城')).map(x=>x.title+'，'+x.description).join(' '):''),generated:true,hasWall:items.some(x=>x.id==='wall'),start:first.start,departureText:`从${hotel()?.name||'东四 / 王府井片区'}出发，建议 ${departureTime} 出门；首段约${first.travelBefore}分钟，另留15分钟到场缓冲。${first.id==='wall'?'长城往返列车时刻尚未录入，出发时间须按已购车票核对。':''}${result.issues.length?' 当前方案存在冲突，请先处理“我的预约”中的提示。':''}`};}
const tabHTML=`<nav class="feature-tabs" role="tablist" aria-label="旅行规划工具"><button id="tab-route" role="tab" aria-selected="true" aria-controls="route-panel" data-view="route">每日行程</button><button id="tab-bookings" role="tab" aria-selected="false" aria-controls="bookings-panel" data-view="bookings">我的预约 <b id="booking-count">0</b></button><button id="tab-map" role="tab" aria-selected="false" aria-controls="map-panel" data-view="map">酒店价格地图</button></nav><div id="plan-banner" class="plan-banner" hidden></div>`;
$('.controls').insertAdjacentHTML('afterend',tabHTML);
const routePanel=document.createElement('section');routePanel.id='route-panel';routePanel.setAttribute('role','tabpanel');routePanel.setAttribute('aria-labelledby','tab-route');$('#day-nav').before(routePanel);routePanel.append($('#day-nav'),$('.workspace'));
routePanel.insertAdjacentHTML('afterend',`<section id="bookings-panel" class="feature-panel" role="tabpanel" aria-labelledby="tab-bookings" hidden><div class="feature-title"><div><div class="eyebrow">YOUR RESERVATIONS</div><h2>先安排约好的，再安排想去的。</h2><p>填写票面日期与计划入场时间，其余景点会围绕预约重新安排。</p></div><button id="restore-original" class="quiet-button">恢复原路线</button></div><div class="planner-layout"><form id="booking-form" class="form-card"><h3 id="booking-form-title">添加一场预约</h3><label>预约景点<select id="booking-poi">${P.BOOKABLE.map(id=>`<option value="${id}">${P.POIS[id].name.replace('（须预约成功）','')}</option>`).join('')}</select></label><label>预约日期<input type="date" id="booking-date" required></label><div class="form-two"><label>入场时间<input type="time" id="booking-time" required value="09:00" min="06:00" max="21:00"></label><label>游览时长（分钟）<input type="number" id="booking-duration" required min="30" max="480" step="15" value="240"></label></div><p class="tiny">票面若为时间段，请填写该时段内你计划入场的时刻。时长是你的游览计划，不是入场有效期。</p><p id="booking-error" class="error-text" role="alert" hidden></p><button type="submit" class="primary">保存预约并生成行程</button><button type="button" class="text-button" id="cancel-booking-edit" hidden>取消编辑</button></form><div><section class="bookings-card"><h3>已记下的预约 <span class="muted" id="reservation-total"></span></h3><div id="reservation-list"></div><button id="generate-plan" class="primary">按这些预约重新生成</button></section><div id="planner-report" class="planner-report" aria-live="polite"></div></div></div><p class="planner-explainer">这里只整理你已经完成的预约，不会代订或更改门票。时间采用北京时间；交通按地点距离作保守估算，不能替代实时导航。预约时刻不会被移动，赶不及会明确提示。排不下的景点会进入待安排清单，清华、北大仍以有效入校预约为准。</p></section>
<section id="map-panel" class="feature-panel" role="tabpanel" aria-labelledby="tab-map" hidden><div class="feature-title"><div><div class="eyebrow">FIND YOUR BASE</div><h2>把住处和预算，放在一张地图上。</h2><p>点价格看酒店，选住处后同步调整每日行程。</p></div><span class="pill">6 家酒店 · 人民币 / 间夜</span></div><div class="map-filters"><label>入住日期<input id="stay-in" type="date"></label><label>退房日期<input id="stay-out" type="date"></label><label>片区<select id="map-area"><option value="all">全部片区</option><option value="central">东四 / 王府井</option><option value="east">东直门 / 国贸</option><option value="south">前门 / 南城</option><option value="northwest">海淀 / 上地</option></select></label><label>每晚预算<select id="map-budget"><option value="all">不限预算</option><option value="600">¥600 以内</option><option value="1000">¥1,000 以内</option><option value="1500">¥1,500 以内</option></select></label><button class="quiet-button" id="map-reset">查看全部位置</button></div><p id="stay-error" class="error-text" role="alert" hidden></p><div class="map-layout"><div class="map-frame"><div id="hotel-map" class="hotel-map" aria-label="北京酒店价格地图"></div><div id="map-error" class="map-error" role="status">正在载入随网页提供的北京离线地图……</div><div class="map-legend"><span>白色价格：页面参考</span><span>绿边价格：你的报价</span><span>红色价格：当前住处</span><span>绿点：部分行程景点</span></div><p class="map-note">底图来自随网页发布的北京 PMTiles 离线包，覆盖城区、海淀、卢沟桥和八达岭，打开地图不会请求境外瓦片服务。参考价核对于2026-09-20，可能对应不同日期、房型和税费条件；只有你填写的报价与所选日期绑定。地图用于比较位置，实际入口以地址导航为准。</p><p id="custom-map-note" class="map-note"></p></div><div><p class="tiny" id="map-results-count"></p><div id="hotel-results" class="hotel-results"></div></div></div></section>`);
function setView(next){view=next;for(const v of ['route','bookings','map']){$('#'+v+'-panel').hidden=v!==next;$('#tab-'+v).setAttribute('aria-selected',v===next?'true':'false');$('#tab-'+v).tabIndex=v===next?0:-1;}if(next==='map'){initMap();refreshMap();requestAnimationFrame(()=>map?.resize());}if(next==='bookings')renderReservations();}
$('.feature-tabs').onclick=e=>{const b=e.target.closest('[data-view]');if(b)setView(b.dataset.view)};
$('.feature-tabs').onkeydown=e=>{const tabs=['route','bookings','map'];if(['ArrowRight','ArrowLeft','Home','End'].includes(e.key)){e.preventDefault();let i=tabs.indexOf(view);i=e.key==='Home'?0:e.key==='End'?2:(i+(e.key==='ArrowRight'?1:2))%3;setView(tabs[i]);$('#tab-'+tabs[i]).focus();}};
function formError(msg){$('#booking-error').hidden=!msg;$('#booking-error').textContent=msg;}
function resetForm(){editing=null;$('#booking-form-title').textContent='添加一场预约';$('#cancel-booking-edit').hidden=true;$('#booking-form button[type=submit]').textContent='保存预约并生成行程';formError('');}
$('#booking-poi').onchange=()=>{$('#booking-duration').value=P.POIS[$('#booking-poi').value].duration;};
$('#cancel-booking-edit').onclick=resetForm;
$('#booking-form').onsubmit=e=>{e.preventDefault();const b={poi:$('#booking-poi').value,date:$('#booking-date').value,time:$('#booking-time').value,duration:Number($('#booking-duration').value)};const error=P.validate(b,state.start);if(error){formError(error);return;}if(state.reservations.some(x=>x.poi===b.poi&&x.poi!==editing)){formError('这个景点已经有预约，请在右侧点击“编辑”修改。');return;}state.reservations=state.reservations.filter(x=>x.poi!==editing);state.reservations.push(b);state.plannerEnabled=true;save();resetForm();render();toast(plan().valid?'已锁定预约并重新安排九天行程':'预约已保留，请先处理时间冲突');};
$('#reservation-list').onclick=e=>{const edit=e.target.closest('[data-edit-booking]'),remove=e.target.closest('[data-remove-booking]');if(edit){const b=state.reservations.find(x=>x.poi===edit.dataset.editBooking);if(!b)return;editing=b.poi;$('#booking-form-title').textContent='修改这场预约';$('#booking-poi').value=b.poi;$('#booking-date').value=b.date;$('#booking-time').value=b.time;$('#booking-duration').value=b.duration;$('#booking-form button[type=submit]').textContent='保存修改并重新生成';$('#cancel-booking-edit').hidden=false;formError('');$('#booking-poi').focus();}if(remove){state.reservations=state.reservations.filter(x=>x.poi!==remove.dataset.removeBooking);if(editing===remove.dataset.removeBooking)resetForm();save();render();toast('已移除预约记录，门票本身不受影响');}};
$('#generate-plan').onclick=()=>{if(!state.start){formError('请先在上方填写出发日期。');$('#start-date').focus();return;}state.plannerEnabled=true;save();render();if(plan().valid){setView('route');toast('已生成行程，未排入的景点可在预约页查看');}else toast('有时间冲突，请先查看提示');};
$('#restore-original').onclick=()=>{state.plannerEnabled=false;save();render();toast('已恢复原路线，预约记录仍然保留');};
function renderReservations(){$('#booking-count').textContent=state.reservations.length;$('#reservation-total').textContent=state.reservations.length+' 场';$('#reservation-list').innerHTML=state.reservations.length?state.reservations.slice().sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)).map(b=>`<article class="booking-row"><div class="booking-clock">${esc(b.time)}<small>${esc(b.date)}</small></div><div class="booking-detail"><strong>${esc(P.POIS[b.poi]?.name||'未知景点')}</strong><p>计划游览 ${esc(b.duration)} 分钟 · 入场时间固定</p></div><div class="booking-actions"><button data-edit-booking="${esc(b.poi)}" aria-label="编辑${esc(P.POIS[b.poi]?.name||'预约')}">编辑</button><button data-remove-booking="${esc(b.poi)}" aria-label="移除${esc(P.POIS[b.poi]?.name||'预约')}">移除</button></div></article>`).join(''):'<p class="empty-bookings">还没有记录预约。<br>从左侧添加第一场，或者先按原路线浏览。</p>';
const result=plan();$('#plan-banner').hidden=!state.plannerEnabled;if(result){const status=result.valid?'已按预约生成：固定入场时间，空档安排其他景点。':'预约方案需要调整：存在时间或日期冲突。';$('#plan-banner').classList.toggle('bad',!result.valid);$('#plan-banner').innerHTML=`<span>${status}${result.unplaced.length?' '+result.unplaced.length+' 个景点待安排 / 备选。':''}</span><button data-open-bookings>查看安排 ↗</button>`;$('#planner-report').innerHTML=`<div class="report-box ${result.valid?'':'bad'}"><strong>${result.valid?'预约时间已保留':'有冲突，请先处理'}</strong>${result.issues.map(t=>`<p>${esc(t)}</p>`).join('')}${result.valid?'<p>已预留估算转场时间。建议再核对当天开放安排、实际交通与餐饮休息。</p>':''}</div>${result.warnings.length?`<div class="report-box warn"><strong>需要核对</strong>${result.warnings.map(t=>`<p>${esc(t)}</p>`).join('')}</div>`:''}${result.unplaced.length?`<div class="report-box warn"><strong>待安排 / 备选 · ${result.unplaced.length} 个</strong><ul>${result.unplaced.map(x=>`<li>${esc(x.name)}：${esc(x.reason)}</li>`).join('')}</ul></div>`:''}`;}else{$('#planner-report').innerHTML='<p class="tiny">当前显示原路线。添加预约或点击“重新生成”后，日期和游览顺序才会调整。</p>';}}
$('#plan-banner').onclick=()=>setView('bookings');
function validStay(){const a=P.dateNumber(state.stayDates.in),b=P.dateNumber(state.stayDates.out);return Number.isFinite(a)&&Number.isFinite(b)&&b>a&&b-a<=30;}
function quoteKey(id){return `${id}|${state.stayDates.in}|${state.stayDates.out}`;}
function priceFor(id){const d=hotelData[id],q=validStay()?state.quotes[quoteKey(id)]:null;return q&&Number.isFinite(q.amount)&&q.amount>0?{amount:q.amount,own:true,context:`${state.stayDates.in} 至 ${state.stayDates.out}；${q.room||'房型未注明'}；${q.tax==='included'?'已确认含税':'税费未确认'}。`,source:q.source||'自行记录',updated:q.updated}: {amount:d.price,own:false,context:d.context,source:d.source,updated:'2026-09-20'};}
function filteredHotels(){const area=$('#map-area').value,budget=$('#map-budget').value;return hotels.filter(h=>(area==='all'||h.area===area)&&(budget==='all'||priceFor(h.id).amount<=Number(budget))).sort((a,b)=>priceFor(a.id).amount-priceFor(b.id).amount);}
function initMap(){
if(map)return;
if(!window.OfflineMap){$('#map-error').hidden=false;$('#map-error').textContent='正在载入随网页提供的北京离线地图……';if(!mapWaiting){mapWaiting=true;window.addEventListener('offline-map-ready',()=>{mapWaiting=false;if(view==='map')initMap();},{once:true});}return;}
const {maplibregl,style}=window.OfflineMap;
const shellStyle={version:8,sources:{},layers:[{id:'paper',type:'background',paint:{'background-color':'#edf0e8'}}]};
map=new maplibregl.Map({container:'hotel-map',style:shellStyle,center:[116.385,39.957],zoom:10.3,minZoom:8.5,maxZoom:13,attributionControl:false,dragRotate:false,pitchWithRotate:false});
map.addControl(new maplibregl.NavigationControl({showCompass:false}),'top-left');
map.addControl(new maplibregl.AttributionControl({compact:true}),'bottom-right');
map.on('error',event=>{$('#map-error').hidden=false;$('#map-error').textContent='离线地图读取失败：'+(event.error?.message||'请刷新后重试')+'。酒店列表与价格仍可使用。';});
map.on('style.load',()=>{if(!map.getSource('beijing')||map.getSource('trip-landmarks'))return;map.addSource('trip-landmarks',{type:'geojson',data:{type:'FeatureCollection',features:['palace','summer','yuanming','lama','bird'].map(id=>{const p=P.POIS[id];return {type:'Feature',properties:{name:p.name},geometry:{type:'Point',coordinates:[p.lon,p.lat]}}})}});map.addLayer({id:'trip-landmarks',type:'circle',source:'trip-landmarks',paint:{'circle-radius':4,'circle-color':'#52694b','circle-stroke-color':'#fff','circle-stroke-width':1}});drawMarkers(filteredHotels());fitMap();});
map.on('idle',()=>{$('#map-error').hidden=true;});
map.on('zoomend',()=>drawMarkers(filteredHotels()));map.on('resize',()=>drawMarkers(filteredHotels()));
map.once('load',()=>map.setStyle(style));
}
function refreshMap(){if(view!=='map')return;const list=filteredHotels();$('#map-results-count').textContent=`显示 ${list.length} / ${hotels.length} 家 · 按当前展示价从低到高`;$('#custom-map-note').textContent=state.hotel==='custom'?'你的自填酒店已作为行程起点；由于未核验精确坐标，暂不在地图上虚构标点。':'';
$('#hotel-results').innerHTML=list.length?list.map(h=>{const d=hotelData[h.id],p=priceFor(h.id);return `<article class="map-hotel-card ${state.hotel===h.id?'is-selected':''}" id="map-card-${h.id}"><div class="hotel-card-head"><h3>${h.name}</h3><div class="price-big">${p.own?'':'≈'}¥${p.amount.toLocaleString('zh-CN',{maximumFractionDigits:2})}<small>${p.own?'你的报价':'页面参考'} / 间夜</small></div></div><p>${h.district} · ${h.address}</p><p class="price-context">${esc(p.context)}<br>${esc(p.source)} · ${esc(p.updated)}${p.own?' 记录':' 核对'}</p><div class="hotel-actions"><button class="primary" data-map-select="${h.id}">${state.hotel===h.id?'当前住处':'选这家'}</button><button data-locate="${h.id}">地图定位</button><a href="${h.url}" target="_blank" rel="noopener noreferrer">官网查实时价 ↗</a></div><details><summary>记录我查到的报价</summary><form class="quote-form" data-quote="${h.id}"><p>${validStay()?esc(state.stayDates.in+' 至 '+state.stayDates.out):'请先在地图上方选择入住和退房日期。'}</p><label>每间每晚均价（人民币）<input name="amount" type="number" required min="1" max="100000" step="0.01" placeholder="例如 688" value="${p.own?p.amount:''}"></label><label>房型 / 人数 / 早餐<input name="room" maxlength="80" placeholder="例如：双床房，2人，含早" value="${p.own?esc(state.quotes[quoteKey(h.id)].room):''}"></label><label>报价来源<input name="source" maxlength="60" placeholder="例如：酒店官网 / 携程" value="${p.own?esc(p.source):''}"></label><label>税费<select name="tax"><option value="unknown">尚未核实是否含税</option><option value="included">已确认含税</option></select></label><div class="quote-buttons"><button class="quiet-button" type="submit">保存报价</button><button type="button" data-remove-quote="${h.id}">清除这组日期的报价</button></div><p class="error-text" data-quote-error role="alert" hidden></p></form></details><details><summary>价格与位置来源</summary><p>参考数值：¥${d.price}，${d.context} <a href="${d.url}" target="_blank" rel="noopener noreferrer">价格来源 ↗</a></p><p>${d.locationNote||'地图点位来自 OpenStreetMap，适合比较位置，并非入口导航。'} <a href="${d.locationSource}" target="_blank" rel="noopener noreferrer">位置来源 ↗</a></p><a href="${esc(mapUrl('东四地铁站',h.name))}" target="_blank" rel="noopener noreferrer">按酒店地址打开导航 ↗</a></details></article>`;}).join(''):'<div class="map-empty">这个预算与片区组合暂时没有匹配酒店。试试提高预算或选择全部片区。</div>';
for(const form of document.querySelectorAll('.quote-form')){const q=state.quotes[quoteKey(form.dataset.quote)];if(q)form.querySelector('[name=tax]').value=q.tax||'unknown';}
drawMarkers(list);}
function drawMarkers(list){if(!map||!window.OfflineMap)return;for(const marker of markers)marker.remove();markers=[];const {maplibregl}=window.OfflineMap,placed=[];for(const h of list){const d=hotelData[h.id],p=priceFor(h.id),point=map.project([d.lon,d.lat]);let offset=0;for(const dy of [0,-38,38,-76,76,-114,114]){if(!placed.some(q=>Math.abs(q.x-point.x)<120&&Math.abs(q.y-(point.y+dy))<34)){offset=dy;break;}}placed.push({x:point.x,y:point.y+offset});const el=document.createElement('button');el.type='button';el.className=`hotel-map-marker hotel-pin-box ${p.own?'own':''} ${state.hotel===h.id?'selected':''}`;el.innerHTML=`${p.own?'':'≈'}¥${p.own?p.amount.toLocaleString('zh-CN',{maximumFractionDigits:2}):Math.round(p.amount)}<small>${p.own?'自填':'参考'}</small>`;el.setAttribute('aria-label',`${h.name}，${p.own?'自填报价':'参考价'}${p.amount}元`);const popup=new maplibregl.Popup({offset:24,maxWidth:'250px'}).setHTML(`<strong>${h.name}</strong><p>${p.own?'你的报价':'页面参考'}：¥${p.amount} / 间夜<br>${esc(p.context)}</p><button data-map-select="${h.id}">以这里为起点 →</button>`);popup.on('open',()=>{const b=popup.getElement()?.querySelector('[data-map-select]');if(b)b.onclick=()=>selectHotel(b.dataset.mapSelect);});markers.push(new maplibregl.Marker({element:el,anchor:'center',offset:[0,offset]}).setLngLat([d.lon,d.lat]).setPopup(popup).addTo(map));}}

$('#map-area').onchange=$('#map-budget').onchange=()=>{refreshMap();fitMap();};
function fitMap(){const list=filteredHotels();if(map&&list.length){const {maplibregl}=window.OfflineMap,bounds=new maplibregl.LngLatBounds();for(const h of list)bounds.extend([hotelData[h.id].lon,hotelData[h.id].lat]);map.fitBounds(bounds,{padding:60,maxZoom:12.6,duration:0});}drawMarkers(list);}
$('#map-reset').onclick=()=>{$('#map-area').value='all';$('#map-budget').value='all';refreshMap();fitMap();};
function changeDates(){state.stayDates={in:$('#stay-in').value,out:$('#stay-out').value};const invalid=!!state.stayDates.in&&!!state.stayDates.out&&!validStay();$('#stay-error').hidden=!invalid;$('#stay-error').textContent='退房须晚于入住，最多比较30晚。请检查日期。';save();refreshMap();}
$('#stay-in').onchange=$('#stay-out').onchange=changeDates;
$('#hotel-results').onclick=e=>{const select=e.target.closest('[data-map-select]'),locate=e.target.closest('[data-locate]'),remove=e.target.closest('[data-remove-quote]');if(select)selectHotel(select.dataset.mapSelect);if(locate){const d=hotelData[locate.dataset.locate];map?.easeTo({center:[d.lon,d.lat],zoom:13,duration:0});}if(remove){delete state.quotes[quoteKey(remove.dataset.removeQuote)];save();refreshMap();toast('已恢复显示参考价');}};
$('#hotel-results').onsubmit=e=>{const form=e.target.closest('[data-quote]');if(!form)return;e.preventDefault();const fd=new FormData(form),amount=Number(fd.get('amount')),error=form.querySelector('[data-quote-error]');if(!validStay()||!Number.isFinite(amount)||amount<1||amount>100000){error.hidden=false;error.textContent=!validStay()?'请先选择有效的入住与退房日期。':'请输入1–100000元之间的报价。';return;}state.quotes[quoteKey(form.dataset.quote)]={amount,source:String(fd.get('source')).trim(),room:String(fd.get('room')).trim(),tax:fd.get('tax'),updated:new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Shanghai'}).format(new Date())};save();refreshMap();toast('报价已保存，地图价格已同步更新');};
function refresh(){if(refreshing)return;refreshing=true;try{renderReservations();$('#stay-in').value=state.stayDates.in||'';$('#stay-out').value=state.stayDates.out||'';if(state.start){$('#booking-date').min=state.start;$('#booking-date').max=P.dateAt(state.start,8);if(!$('#booking-date').value)$('#booking-date').value=P.dateAt(state.start,2);}refreshMap();const palaceDay=plan()?.days.findIndex(items=>items.some(x=>x.id==='palace'));if(state.plannerEnabled&&palaceDay>=0&&Number.isFinite(P.dateNumber(state.start))){let d=new Date(P.dateAt(state.start,palaceDay)+'T12:00:00');d.setDate(d.getDate()-7);$('#check-palace').nextElementSibling?.querySelector('label')?.replaceChildren(document.createTextNode(`故宫预约 · ${d.getMonth()+1}月${d.getDate()}日20:00放票`));}}finally{refreshing=false;}}
window.BeijingFeatures={day:plannedDay,refresh,plan,setView};
$('#sources-content').insertAdjacentHTML('beforeend','<p>新增预约排程：固定预约优先，其他景点按游览时长、距离和保守游览时段插入；非实时交通，也不是最优路径求解。地图价格均为参考快照或你的自填报价，不代表当前可订房价。北京离线底图为2026-09-20生成的 PMTiles 切片，数据 © OpenStreetMap contributors；渲染使用 MapLibre GL JS，归档读取使用 PMTiles。</p>');
const baseExport=itineraryText;$('#export').onclick=()=>{const result=plan();let text=baseExport();if(result)text+='\n\n预约排程检查\n'+(result.issues.length?result.issues.join('\n'):'未发现预约时间重叠；请继续核对实际交通与景点开放。')+'\n'+result.warnings.join('\n')+'\n待安排 / 备选：\n'+result.unplaced.map(p=>p.name+'：'+p.reason).join('\n');const blob=new Blob(['\ufeff'+text],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='北京九日旅行手册.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);toast('已导出行程及预约冲突、待安排清单');};
render();setView('route');
if(document.modelContext?.registerTool){const lifecycle=new AbortController();const register=t=>{try{Promise.resolve(document.modelContext.registerTool(t,{signal:lifecycle.signal})).catch(()=>{})}catch{}};register({name:'configure_beijing_reservations',description:'Replace the locally saved reservation list and regenerate the visible nine-day itinerary. Does not book or change real tickets.',inputSchema:{type:'object',properties:{startDate:{type:'string'},reservations:{type:'array',maxItems:8,items:{type:'object',properties:{poi:{type:'string',enum:P.BOOKABLE},date:{type:'string'},time:{type:'string'},duration:{type:'integer',minimum:30,maximum:480}},required:['poi','date','time','duration'],additionalProperties:false}}},required:['startDate','reservations'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:input=>{if(!input||Object.keys(input).some(k=>!['startDate','reservations'].includes(k))||!Array.isArray(input.reservations)||input.reservations.length>8||!Number.isFinite(P.dateNumber(input.startDate)))throw new Error('Invalid trip inputs');const seen=new Set();for(const b of input.reservations){if(!b||Object.keys(b).some(k=>!['poi','date','time','duration'].includes(k)))throw new Error('Invalid reservation');const error=P.validate(b,input.startDate);if(error||seen.has(b.poi))throw new Error(error||'Duplicate reservation');seen.add(b.poi);}state.start=input.startDate;state.reservations=structuredClone(input.reservations);state.plannerEnabled=true;save();render();setView('bookings');return {valid:plan().valid,issues:plan().issues,warnings:plan().warnings,unplaced:plan().unplaced.map(x=>x.name)};}});window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
})();
